version: '3'

services:
  php:
    container_name: "prdg_php"
    build: docker/php-apache/
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - .:/var/www
      - /var/www/docker
    env_file:
      - .env
    user: 1000:1000
  sqlserver:
    container_name: "prdg_mssql"
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/data/prdg/mssql:/var/opt/mssql/data
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
    user: root